<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP Blank Template</title>
</head>
<body>
    <h1>Welcome to the PHP Page</h1>
    
    

    <!-- You can add more HTML here -->

</body>
</html>



<?php
        // PHP code goes here
        echo "<p>This content was generated by PHP.</p>";
        ?>